[tool.poetry]
name = "pycounts_ac"
version = "0.1.0"
description = "rfrfr"
authors = ["Alan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.10.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
